### ISSUE TITLE
Question about training skill: 'Early Stopping!~' 

### ISSUE THREAD

**Issue by Garfield-kh** [EricGuo5513/TM2T#3]
Hi, thank you very much for sharing this intereting work.
I tried download the data `HumanML3D` and re-run the whole process.
While the final_evaluation meet error, the qualitative result looks very nice.

Here I want to ask some questions about the training process, which I am not sure if I did it right or not.

**train_vq_tokenizer_v3.py**

1. I found there is a `ema` and `cmt` opinion for `quantizer`, while some blog says `ema` is faster, may I ask if `ema` works better in this task?
2. When I run the **train_vq_tokenizer_v3.py**, I found that the `max_epoch` is 300, while it takes me 24 hours for about 50 epoch. If I increased the `batch_size` , and got a lower `val_loss`, will that faster the training process without hurt the performance?
3. I found that the `break` after 'Early Stopping!~' is comment out, is that because we need to try ckpt from longer training?

**train_m2t_transformer.py**
1. When I run the **train_m2t_transformer.py**, the val_los stop decrease after 20 mins as shown in the Fig below, is this normal? Or would be appreciated if you could provide us log file for double check... >.<
![m2t](https://user-images.githubusercontent.com/37209147/186605019-822a2315-b2c3-49b7-8fe2-0d0c060edea8.png)

Thank you!

**Comment by EricGuo5513** [comment]
Hi, 

1. I have tried the "ema" method, but it does not work well. Not sure if there is any implementation error. I think using "ema" or "cmt" is not a major factor here.
2. Large batch size should not hurt the performance. I didn't try other batch sizes. From my experience, the VQ-VAE is much harder to train than a usual auto-encoder. It necessitates large model, so I use resblocks to increase the model size. Anyway, lower "val_loss" is a good sign, and ususally you don't need to run 300 epoches. The training process is quite stable, and you can early stop it as long as it converge.
3. It is because I have time and have GPU. Hahaha. And the training process is stable, so I don't care so much whether it stops early or not.
4. Training "motion-to-text" and "text-to-motion" are quite fast that it ususally reaches best performance within around 10 epoches. So it should be normal. You could also check the results. I want to show you the log file but unfortunately my server was broken down recently.

**Comment by Garfield-kh** [comment]
Thank you for the answering, this helps a lot. ^-^
